apiVersion: v1
kind: Service
metadata:  
  name: pricer-service
spec:
  selector:    
    app: pricer
  type: LoadBalancer
  ports:  
  - name: http
    port: 3000
    targetPort: 80
    protocol: TCP
