apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricer
  labels:
    app: pricer
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricer
  template:
    metadata:
      labels:
        app: pricer
    spec:
      containers:
        - name: pricer
          image: data-pricer
          imagePullPolicy: Never
          ports:
          - name: http
            containerPort: 80